In [1]:
import pandas as pd
import os
from pathlib import Path
import numpy as np

In [2]:
## Estabelecendo diretórios base
diretorio_src_etl = os.getcwd()
diretorio_src = Path(diretorio_src_etl).parent.absolute()
diretorio_base = Path(diretorio_src).parent.absolute()
diretorio_data = os.path.join(diretorio_base, 'data')

# Bronze
diretorio_bronze = os.path.join(diretorio_data, 'bronze')
diretorio_sim_bronze = os.path.join(diretorio_bronze, 'sim')
diretorio_sim_bronze_csv = os.path.join(diretorio_sim_bronze, 'csv')

# Silver
diretorio_silver = os.path.join(diretorio_data, 'silver')
diretorio_sim_silver = os.path.join(diretorio_silver, 'sim')
diretorio_sim_silver_tsv = os.path.join(diretorio_sim_silver, 'tsv')

## Criação de pastas para armazenar os arquivos
os.makedirs(os.path.join(diretorio_data), exist_ok=True)
os.makedirs(os.path.join(diretorio_silver), exist_ok=True)
os.makedirs(os.path.join(diretorio_sim_silver), exist_ok=True)
os.makedirs(os.path.join(diretorio_sim_silver_tsv), exist_ok=True)

In [3]:
arquivos_csv = [arquivo for arquivo in os.listdir(diretorio_sim_bronze_csv) if arquivo.endswith("csv")]
arquivos_csv = arquivos_csv[-2:]
arquivos_tsv = [arquivo.rstrip("csv") + "tsv" for arquivo in arquivos_csv]
arquivos_tsv

['DOTO2010.tsv', 'DOTO2011.tsv']

In [4]:
for arquivo_csv, arquivo_tsv in zip(arquivos_csv, arquivos_tsv):
    df = pd.read_csv(os.path.join(diretorio_sim_bronze_csv, arquivo_csv), sep=',')
    # # Trocar "NA" por np.nan (ou None, ambos representam valores nulos em Pandas)
    # df.replace("NA", np.nan, inplace=True)
    # df.replace("", np.nan, inplace=True)
    # # Remover aspas das colunas que são de tipo string
    # df = df.applymap(lambda x: x.strip('"') if isinstance(x, str) else x)
    # # Aplicar a função e criar a nova coluna IDADE_ANOS
    # df['IDADE_ANOS'] = df['NU_IDADE_N'].apply(convert_to_years)
    # df = df.rename(columns=column_map)
    # df = df[colunas_importantes]


    # # Itera sobre cada coluna e tenta converter para inteiro
    # for column in columns_to_convert:
    #     df[column] = pd.to_numeric(df[column], errors='coerce').astype('Int64')
    # df.to_csv(os.path.join(diretorio_sim_silver_tsv, arquivo_tsv), sep='\t', index=False)

In [5]:
df.head()

,CONTADOR,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,DTNASC,IDADE,SEXO,RACACOR,...,DTRECORIGA,CAUSAMAT,ESC2010,ESCMAE2010,STDOEPIDEM,STDONOVA,DTCADINV,TPOBITOCOR,DTCADINF,MORTEPARTO
0,1,1,2,4012011,0700,817.0,24081922.0,488,1,4.0,...,14022011.0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN
1,2,1,2,8032011,1800,NaN,13091928.0,482,2,2.0,...,13062011.0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN
2,3,1,2,2012011,1000,817.0,7091975.0,435,2,4.0,...,21022011.0,NaN,NaN,NaN,0,0,25072011.0,9.0,NaN,NaN
3,4,1,2,28042011,0355,NaN,25041941.0,470,2,1.0,...,6052011.0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN
4,5,1,2,30082011,0530,NaN,19101928.0,482,2,4.0,...,5092011.0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN

In [6]:
df.columns

Index(['CONTADOR', 'ORIGEM', 'TIPOBITO', 'DTOBITO', 'HORAOBITO', 'NATURAL',
       'DTNASC', 'IDADE', 'SEXO', 'RACACOR', 'ESTCIV', 'ESC', 'OCUP',
       'CODMUNRES', 'LOCOCOR', 'CODESTAB', 'CODMUNOCOR', 'IDADEMAE', 'ESCMAE',
       'OCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'GRAVIDEZ', 'GESTACAO', 'PARTO',
       'OBITOPARTO', 'PESO', 'OBITOGRAV', 'OBITOPUERP', 'ASSISTMED', 'EXAME',
       'CIRURGIA', 'NECROPSIA', 'LINHAA', 'LINHAB', 'LINHAC', 'LINHAD',
       'LINHAII', 'CAUSABAS', 'COMUNSVOIM', 'DTATESTADO', 'CIRCOBITO',
       'ACIDTRAB', 'FONTE', 'TPPOS', 'DTINVESTIG', 'CAUSABAS_O', 'DTCADASTRO',
       'ATESTANTE', 'FONTEINV', 'DTRECEBIM', 'DTRECORIG', 'DTRECORIGA',
       'CAUSAMAT', 'ESC2010', 'ESCMAE2010', 'STDOEPIDEM', 'STDONOVA',
       'DTCADINV', 'TPOBITOCOR', 'DTCADINF', 'MORTEPARTO'],
      dtype='object')